name: Test pipeline

on: push

jobs:
    first job:
        runs-on: ubuntu-ubutu

        steps:
            -name: checkoutcode
            -uses: actions/checkout@v3

            -name: Run test
             run: node test.js
            
