name: Test pipeline

on: push

jobs:
    firstjob:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3
              with:
                node-version: '18'

                -name: test
                run: node test.js